# Generated by Django 5.1.4 on 2025-01-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olmsapp", "0002_add_admin_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
